# Generated by Django 4.2.1 on 2023-07-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='pokemon/')),
                ('type1', models.CharField(choices=[('ACIER', 'Acier'), ('COMBAT', 'Combat'), ('DRAGON', 'Dragon'), ('EAU', 'Eau'), ('ELECTRIK', 'Électrique'), ('FEE', 'Fée'), ('FEU', 'Feu'), ('GLACE', 'Glace'), ('INSECTE', 'Insecte'), ('NORMAL', 'Normal'), ('PLANTE', 'Plante'), ('POISON', 'Poison'), ('PSY', 'Psy'), ('ROCHE', 'Roche'), ('SOL', 'Sol'), ('SPECTRE', 'Spectre'), ('TENEBRES', 'Ténèbres'), ('VOL', 'Vol')], default=('ACIER', 'Acier'), max_length=15)),
                ('type2', models.CharField(choices=[('ACIER', 'Acier'), ('COMBAT', 'Combat'), ('DRAGON', 'Dragon'), ('EAU', 'Eau'), ('ELECTRIK', 'Électrique'), ('FEE', 'Fée'), ('FEU', 'Feu'), ('GLACE', 'Glace'), ('INSECTE', 'Insecte'), ('NORMAL', 'Normal'), ('PLANTE', 'Plante'), ('POISON', 'Poison'), ('PSY', 'Psy'), ('ROCHE', 'Roche'), ('SOL', 'Sol'), ('SPECTRE', 'Spectre'), ('TENEBRES', 'Ténèbres'), ('VOL', 'Vol')], max_length=15, null=True)),
                ('pv', models.IntegerField()),
                ('attaque', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('attaque_spe', models.IntegerField()),
                ('defense_spe', models.IntegerField()),
                ('vitesse', models.IntegerField()),
            ],
        ),
    ]
