# Generated by Django 4.2.1 on 2023-07-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='categorie',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='poids',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='taille',
            field=models.FloatField(default=0),
        ),
    ]
