# Generated by Django 4.2.1 on 2023-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pokemon_categorie_pokemon_description_pokemon_poids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(choices=[('Acier', 'Acier'), ('Combat', 'Combat'), ('Dragon', 'Dragon'), ('Eau', 'Eau'), ('Électrique', 'Électrique'), ('Fée', 'Fée'), ('Feu', 'Feu'), ('Glace', 'Glace'), ('Insecte', 'Insecte'), ('Normal', 'Normal'), ('Plante', 'Plante'), ('Poison', 'Poison'), ('Psy', 'Psy'), ('Roche', 'Roche'), ('Sol', 'Sol'), ('Spectre', 'Spectre'), ('Ténèbres', 'Ténèbres'), ('Vol', 'Vol')], default=('Acier', 'Acier'), max_length=15),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(choices=[('Acier', 'Acier'), ('Combat', 'Combat'), ('Dragon', 'Dragon'), ('Eau', 'Eau'), ('Électrique', 'Électrique'), ('Fée', 'Fée'), ('Feu', 'Feu'), ('Glace', 'Glace'), ('Insecte', 'Insecte'), ('Normal', 'Normal'), ('Plante', 'Plante'), ('Poison', 'Poison'), ('Psy', 'Psy'), ('Roche', 'Roche'), ('Sol', 'Sol'), ('Spectre', 'Spectre'), ('Ténèbres', 'Ténèbres'), ('Vol', 'Vol')], max_length=15, null=True),
        ),
    ]
