# Generated by Django 4.2.1 on 2023-07-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pokemon_evo_pokemon_preevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='preevo',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preevo', to='app.pokemon'),
        ),
    ]
