# Generated by Django 4.2.1 on 2023-07-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pokemon_evo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=250)),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='app.pokemon')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution', to='app.pokemon')),
            ],
        ),
    ]
