# Generated by Django 4.2.1 on 2023-07-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_game_alter_pokemon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
        migrations.CreateModel(
            name='PokemonInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='app.game')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='app.pokemon')),
            ],
        ),
    ]
