# Generated by Django 4.2.1 on 2023-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_pokemon_description_pokemoninstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='jaquette',
            field=models.ImageField(upload_to='jaquette/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(upload_to='pokemon/'),
        ),
    ]
