# Generated by Django 4.2.1 on 2023-07-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_extension_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='pokemons',
            field=models.ManyToManyField(related_name='users', to='app.pokemoninstance'),
        ),
    ]
